# Generated by Django 4.2.6 on 2023-10-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_customusermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.department'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend_api.jobtitle'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='seniority',
            field=models.CharField(choices=[('REG', 'Regular'), ('JR', 'Junior'), ('MID', 'Middle'), ('SR', 'Senior')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='telephone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
