# Generated by Django 4.2.6 on 2023-11-01 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_alter_customusermodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='seniority',
            field=models.CharField(choices=[('REG', 'Regular'), ('JR', 'Junior'), ('MID', 'Middle'), ('SR', 'Senior')], max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pushed_on', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasked_employees_set', to=settings.AUTH_USER_MODEL)),
                ('tasked_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='taskers_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_points', models.PositiveIntegerField()),
                ('feedback', models.TextField()),
                ('goals_achieved', models.TextField()),
                ('improvement_areas', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_employees_set', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reviewers_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=9)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bonuses', models.DecimalField(decimal_places=2, max_digits=9)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('day_of_monthly_payment', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_leave', models.CharField(choices=[('sick leave', 'sick leave'), ('anual leave', 'anual leave'), ('funeral leave', 'funeral leave'), ('marriage leave', 'marriage leave')], max_length=14)),
                ('days_needed', models.PositiveIntegerField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBallance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_ballance', models.PositiveIntegerField(default=20)),
                ('marriage_ballance', models.PositiveIntegerField(default=7)),
                ('funeral_ballance', models.PositiveIntegerField(default=2)),
                ('sick_ballance', models.PositiveIntegerField(default=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.TimeField(auto_now_add=True)),
                ('check_out', models.TimeField()),
                ('current_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
