# Generated by Django 4.2.6 on 2023-11-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_remove_customusermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='seniority',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], max_length=7, null=True),
        ),
    ]
