# Generated by Django 4.2.6 on 2023-11-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_alter_customusermodel_seniority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Gender-fluid', 'Gender-fluid'), ('Non-binary', 'Non-binary')]),
        ),
    ]
